apiVersion: v1
kind: Pod
metadata: 
  name: flask-app-pod
  labels:
    tool: flask
    tier: web-app
    part: backend
    type: pod
spec:
  containers:
    - name: flask-app
      image: flask_pgs-flask-app:latest
      imagePullPolicy: Never
      ports:
        - containerPort: 8000
      env:
        - name: DB_URL
          value: "postgresql://harry:password@postgres-service:5432/flask_db"