apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
  labels:
    tool: flask
    tier: web-app
    part: backend
    type: deployment
spec:
  replicas: 4
  template: 
    metadata: 
      name: flask-app-pod
      labels:
        tool: flask
        tier: web-app
        part: backend
        type: pod
    spec:
      containers:
        - name: flask-app
          image: flask_pgs-flask-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: DB_URL
              value: "postgresql://harry:password@postgres-service:5432/flask_db"
  selector:
    matchLabels:
        tool: flask
        tier: web-app
        part: backend
        type: pod
