apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  labels:
    tool: flask
    tier: web-app
    part: backend
    type: service
spec:
  type: NodePort
  ports:
    - targetPort: 8000
      port: 8000
      nodePort: 30010
  selector:
    tool: flask
    tier: web-app
    part: backend
    type: pod