apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    tool: postgres
    tier: database
    part: backend
    type: service
spec:
  type: ClusterIP
  ports:
    - targetPort: 5432
      port: 5432
  selector:
    tool: postgres
    tier: database
    part: backend
    type: pod