apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    tool: postgres
    tier: database
    part: backend
    type: pod
spec:
  containers:
    - name: postgres
      image: postgres:latest
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_USER
          value: "harry"
        - name: POSTGRES_DB
          value: "flask_db"
        - name: POSTGRES_PASSWORD
          value: "password"